"""西游记人物数据"""

CHARACTERS = [
    # === 取经团队 ===
    {
        "character_id": "tangseng",
        "name": "唐僧",
        "full_name": "唐僧/Tripitaka",
        "dharma_name": "玄奘",
        "title": "旃檀功德佛",
        "race": "凡人",
        "faction": "佛门",
        "role": "取经人",
        "cultivation": "金蝉子转世",
        "description": "金蝉子转世，大唐高僧，奉旨西天取经",
    },
    {
        "character_id": "sunwukong",
        "name": "孙悟空",
        "full_name": "孙悟空/Sun Wukong",
        "dharma_name": "行者",
        "title": "斗战胜佛",
        "race": "石猴",
        "faction": "佛门",
        "role": "大徒弟",
        "cultivation": "太乙散仙",
        "description": "花果山石猴，大闹天宫后被如来镇压，随唐僧西行取经",
    },
    {
        "character_id": "zhubajie",
        "name": "猪八戒",
        "full_name": "猪八戒/Zhu Bajie",
        "dharma_name": "悟能",
        "title": "净坛使者",
        "race": "猪妖",
        "faction": "佛门",
        "role": "二徒弟",
        "cultivation": "天蓬元帅转世",
        "description": "原天蓬元帅，因调戏嫦娥被贬下凡，随唐僧西行取经",
    },
    {
        "character_id": "shaheshang",
        "name": "沙僧",
        "full_name": "沙僧/Sha Wujing",
        "dharma_name": "悟净",
        "title": "金身罗汉",
        "race": "水怪",
        "faction": "佛门",
        "role": "三徒弟",
        "cultivation": "卷帘大将转世",
        "description": "原卷帘大将，因失手打碎琉璃盏被贬流沙河，随唐僧西行取经",
    },
    {
        "character_id": "baimalong",
        "name": "白龙马",
        "full_name": "白龙马/White Dragon Horse",
        "dharma_name": "",
        "title": "八部天龙",
        "race": "龙族",
        "faction": "佛门",
        "role": "坐骑",
        "cultivation": "西海龙王三太子",
        "description": "西海龙王三太子，因纵火烧毁殿上明珠被判死罪，后化作白马驮唐僧取经",
    },

    # === 天庭 ===
    {
        "character_id": "yuhuang",
        "name": "玉皇大帝",
        "full_name": "玉皇大帝/Jade Emperor",
        "dharma_name": "",
        "title": "三界之主",
        "race": "神仙",
        "faction": "天庭",
        "role": "天帝",
        "cultivation": "万劫之祖",
        "description": "三界最高统治者，掌管天庭",
    },
    {
        "character_id": "taishanglaojun",
        "name": "太上老君",
        "full_name": "太上老君/Laozi",
        "dharma_name": "",
        "title": "道德天尊",
        "race": "神仙",
        "faction": "天庭",
        "role": "道教之祖",
        "cultivation": "混元大罗金仙",
        "description": "道教之祖，炼丹之术冠绝三界",
    },
    {
        "character_id": "guanyin",
        "name": "观音菩萨",
        "full_name": "观音菩萨/Guanyin",
        "dharma_name": "",
        "title": "大慈大悲救苦救难",
        "race": "菩萨",
        "faction": "佛门",
        "role": "取经策划",
        "cultivation": "菩萨",
        "description": "奉如来之命寻找取经人，一路暗中保护取经团队",
    },
    {
        "character_id": "erlangshen",
        "name": "二郎神",
        "full_name": "二郎神/Erlang Shen",
        "dharma_name": "",
        "title": "显圣二郎真君",
        "race": "神仙",
        "faction": "天庭",
        "role": "战神",
        "cultivation": "八九玄功",
        "description": "玉帝外甥，天庭第一战将，曾降伏孙悟空",
    },
    {
        "character_id": "nezhaw",
        "name": "哪吒",
        "full_name": "哪吒/Nezha",
        "dharma_name": "",
        "title": "三太子",
        "race": "神仙",
        "faction": "天庭",
        "role": "先锋",
        "cultivation": "三头六臂",
        "description": "托塔天王李靖三子，天庭先锋大将",
    },

    # === 佛门 ===
    {
        "character_id": "rulai",
        "name": "如来佛祖",
        "full_name": "如来佛祖/Buddha",
        "dharma_name": "",
        "title": "释迦牟尼佛",
        "race": "佛",
        "faction": "佛门",
        "role": "佛祖",
        "cultivation": "万佛之祖",
        "description": "西天灵山佛祖，镇压孙悟空，发起取经大业",
    },

    # === 妖魔（精选代表性妖魔）===
    {
        "character_id": "niumowang",
        "name": "牛魔王",
        "full_name": "牛魔王/Bull Demon King",
        "dharma_name": "",
        "title": "平天大圣",
        "race": "牛妖",
        "faction": "妖界",
        "role": "妖王",
        "cultivation": "大罗金仙",
        "description": "孙悟空结义大哥，七大圣之首，火焰山大战取经团队",
    },
    {
        "character_id": "baigujing",
        "name": "白骨精",
        "full_name": "白骨精/White Bone Spirit",
        "dharma_name": "",
        "title": "白骨夫人",
        "race": "尸妖",
        "faction": "妖界",
        "role": "妖精",
        "cultivation": "千年修炼",
        "description": "白虎岭尸魔，三戏唐僧致孙悟空被逐",
    },
    {
        "character_id": "honghaier",
        "name": "红孩儿",
        "full_name": "红孩儿/Red Boy",
        "dharma_name": "善财童子",
        "title": "圣婴大王",
        "race": "妖族",
        "faction": "妖界",
        "role": "妖王",
        "cultivation": "三昧真火",
        "description": "牛魔王之子，会三昧真火，后被观音收为善财童子",
    },
    {
        "character_id": "huoyan_shanshen",
        "name": "火焰山土地",
        "full_name": "火焰山土地/Flame Mountain Guardian",
        "dharma_name": "",
        "title": "土地神",
        "race": "神仙",
        "faction": "天庭",
        "role": "土地",
        "cultivation": "地仙",
        "description": "火焰山土地，告知取经人借芭蕉扇灭火之法",
    },
    {
        "character_id": "tieshan_gongzhu",
        "name": "铁扇公主",
        "full_name": "铁扇公主/Princess Iron Fan",
        "dharma_name": "",
        "title": "罗刹女",
        "race": "妖族",
        "faction": "妖界",
        "role": "妖王",
        "cultivation": "芭蕉扇",
        "description": "牛魔王之妻，红孩儿之母，持有芭蕉扇",
    },
    {
        "character_id": "huangmei_laofo",
        "name": "黄眉老佛",
        "full_name": "黄眉老佛/Yellow Brow",
        "dharma_name": "",
        "title": "小雷音寺佛祖",
        "race": "妖族",
        "faction": "妖界",
        "role": "妖王",
        "cultivation": "人种袋/金铙",
        "description": "弥勒佛座下童子，盗了人种袋和金铙在小雷音寺假冒佛祖",
    },
]
