"""西游记事件数据（八十一难精选 + 关键情节）"""

EVENTS = [
    # === 取经前传 ===
    {
        "event_id": "evt_p001",
        "name": "石猴出世",
        "chapter": "第一回",
        "trial_number": 0,
        "category": "天命",
        "location": "花果山",
        "description": "花果山仙石孕育石猴，目运两道金光惊动天庭",
    },
    {
        "event_id": "evt_p002",
        "name": "大闹天宫",
        "chapter": "第四至七回",
        "trial_number": 0,
        "category": "天命",
        "location": "天宫",
        "description": "孙悟空偷蟠桃盗仙丹大闹天宫，被如来镇压于五行山下",
    },
    {
        "event_id": "evt_p003",
        "name": "观音寻找取经人",
        "chapter": "第八至十二回",
        "trial_number": 0,
        "category": "天命",
        "location": "长安",
        "description": "观音奉如来之命，至东土寻找取经人，安排唐僧西行取经",
    },

    # === 八十一难（按回目推进精选关键劫难）===
    {
        "event_id": "evt_001",
        "name": "金蝉遭贬",
        "chapter": "第八回",
        "trial_number": 1,
        "category": "天命",
        "location": "灵山",
        "description": "金蝉子因不听说法被贬转生东土，此为第一难",
    },
    {
        "event_id": "evt_002",
        "name": "出胎几杀",
        "chapter": "第九回",
        "trial_number": 2,
        "category": "天命",
        "location": "洪州",
        "description": "唐僧出生即逢难，父亲被害母亲被掳",
    },
    {
        "event_id": "evt_004",
        "name": "收伏悟空",
        "chapter": "第十四回",
        "trial_number": 4,
        "category": "收徒",
        "location": "五行山",
        "description": "唐僧揭封释悟空，观音赐紧箍咒收伏心猿",
    },
    {
        "event_id": "evt_005",
        "name": "收伏八戒",
        "chapter": "第十八回",
        "trial_number": 5,
        "category": "收徒",
        "location": "高老庄",
        "description": "唐僧收猪八戒为二徒弟，八戒拜别高老庄",
    },
    {
        "event_id": "evt_006",
        "name": "收伏沙僧",
        "chapter": "第二十二回",
        "trial_number": 6,
        "category": "收徒",
        "location": "流沙河",
        "description": "唐僧收沙悟净为三徒弟，取经团队齐备",
    },
    {
        "event_id": "evt_010",
        "name": "三打白骨精",
        "chapter": "第二十七回",
        "trial_number": 10,
        "category": "妖魔",
        "location": "白虎岭",
        "description": "白骨精三戏唐僧，悟空三打被逐，师徒分离",
    },
    {
        "event_id": "evt_015",
        "name": "偷吃人参果",
        "chapter": "第二十四至二十六回",
        "trial_number": 15,
        "category": "仙缘",
        "location": "五庄观",
        "description": "悟空偷吃人参果推倒果树，请观音复活果树方化解",
    },
    {
        "event_id": "evt_020",
        "name": "黄袍怪",
        "chapter": "第二十八至三十一回",
        "trial_number": 20,
        "category": "妖魔",
        "location": "碗子山",
        "description": "黄袍怪掳走唐僧，八戒请回悟空救师",
    },
    {
        "event_id": "evt_025",
        "name": "平顶山金角银角",
        "chapter": "第三十二至三十五回",
        "trial_number": 25,
        "category": "妖魔",
        "location": "平顶山",
        "description": "金角大王银角大王持五件法宝为难取经团队",
    },
    {
        "event_id": "evt_030",
        "name": "车迟国斗法",
        "chapter": "第四十四至四十六回",
        "trial_number": 30,
        "category": "斗法",
        "location": "车迟国",
        "description": "与虎力大仙、鹿力大仙、羊力大仙斗法三场",
    },
    {
        "event_id": "evt_036",
        "name": "通天河金鱼精",
        "chapter": "第四十七至四十九回",
        "trial_number": 36,
        "category": "妖魔",
        "location": "通天河",
        "description": "灵感大王（金鱼精）作祟通天河，观音收鱼精",
    },
    {
        "event_id": "evt_040",
        "name": "女儿国",
        "chapter": "第五十三至五十五回",
        "trial_number": 40,
        "category": "情劫",
        "location": "女儿国",
        "description": "唐僧误饮子母河水和亲女儿国国王，蝎子精掳走唐僧",
    },
    {
        "event_id": "evt_045",
        "name": "真假美猴王",
        "chapter": "第五十六至五十八回",
        "trial_number": 45,
        "category": "心魔",
        "location": "西天路上",
        "description": "六耳猕猴假冒孙悟空，如来识破真相",
    },
    {
        "event_id": "evt_050",
        "name": "火焰山借扇",
        "chapter": "第五十九至六十一回",
        "trial_number": 50,
        "category": "天险",
        "location": "火焰山",
        "description": "三借芭蕉扇灭火焰山，大战牛魔王",
    },
    {
        "event_id": "evt_055",
        "name": "小雷音寺",
        "chapter": "第六十五至六十六回",
        "trial_number": 55,
        "category": "妖魔",
        "location": "小雷音寺",
        "description": "黄眉老佛假冒佛祖困住取经团队，弥勒佛收服",
    },
    {
        "event_id": "evt_060",
        "name": "盘丝洞蜘蛛精",
        "chapter": "第七十二至七十三回",
        "trial_number": 60,
        "category": "妖魔",
        "location": "盘丝洞",
        "description": "七个蜘蛛精与蜈蚣精多眼怪为难取经团队",
    },
    {
        "event_id": "evt_065",
        "name": "狮驼岭三大魔王",
        "chapter": "第七十四至七十七回",
        "trial_number": 65,
        "category": "妖魔",
        "location": "狮驼岭",
        "description": "青狮、白象、大鹏三魔王最难降伏，如来亲降大鹏",
    },
    {
        "event_id": "evt_070",
        "name": "比丘国救子",
        "chapter": "第七十八至七十九回",
        "trial_number": 70,
        "category": "妖魔",
        "location": "比丘国",
        "description": "白鹿精蛊惑国王取小儿心肝，悟空救儿童",
    },
    {
        "event_id": "evt_075",
        "name": "无底洞地涌夫人",
        "chapter": "第八十至八十三回",
        "trial_number": 75,
        "category": "妖魔",
        "location": "无底洞",
        "description": "金鼻白毛老鼠精掳走唐僧，托塔天王收服义女",
    },
    {
        "event_id": "evt_080",
        "name": "天竺国玉兔精",
        "chapter": "第九十三至九十五回",
        "trial_number": 80,
        "category": "妖魔",
        "location": "天竺国",
        "description": "玉兔精假扮公主欲招唐僧为驸马，太阴星君收服",
    },
    {
        "event_id": "evt_081",
        "name": "灵山取经",
        "chapter": "第九十八回",
        "trial_number": 81,
        "category": "天命",
        "location": "灵山",
        "description": "抵达灵山，阿傩迦叶索要人事，唐僧交出紫金钵盂取得真经",
    },
]
