"""西游记地点数据"""

LOCATIONS = [
    # === 取经路线关键地点 ===
    {
        "location_id": "huaguoshan",
        "name": "花果山",
        "full_name": "花果山/Mountain of Flowers and Fruit",
        "location_type": "仙山",
        "faction": "妖界",
        "region": "东胜神洲",
        "danger_level": 0,
        "description": "东胜神洲傲来国花果山，孙悟空出生之地",
    },
    {
        "location_id": "wuxingshan",
        "name": "五行山",
        "full_name": "五行山/Five Elements Mountain",
        "location_type": "山",
        "faction": "天庭",
        "region": "南赡部洲",
        "danger_level": 0,
        "description": "如来将孙悟空镇压之处，后改名两界山",
    },
    {
        "location_id": "gaolaozhuang",
        "name": "高老庄",
        "full_name": "高老庄/Gao Village",
        "location_type": "庄院",
        "faction": "人间",
        "region": "乌斯藏国",
        "danger_level": 1,
        "description": "猪八戒被收服之处",
    },
    {
        "location_id": "liushahe",
        "name": "流沙河",
        "full_name": "流沙河/Flowing Sand River",
        "location_type": "河流",
        "faction": "人间",
        "region": "南赡部洲",
        "danger_level": 2,
        "description": "沙僧被收服之处，八百里流沙",
    },
    {
        "location_id": "baiguling",
        "name": "白虎岭",
        "full_name": "白虎岭/White Tiger Ridge",
        "location_type": "山岭",
        "faction": "妖界",
        "region": "宛子山",
        "danger_level": 3,
        "description": "白骨精盘踞之地，三戏唐僧",
    },
    {
        "location_id": "huoyanshan",
        "name": "火焰山",
        "full_name": "火焰山/Flame Mountain",
        "location_type": "山",
        "faction": "妖界",
        "region": "西牛贺洲",
        "danger_level": 4,
        "description": "八百里火焰山，需芭蕉扇灭火方得通过",
    },
    {
        "location_id": "cuoyunshan",
        "name": "翠云山",
        "full_name": "翠云山/Emerald Cloud Mountain",
        "location_type": "仙山",
        "faction": "妖界",
        "region": "西牛贺洲",
        "danger_level": 3,
        "description": "铁扇公主居住之所，芭蕉洞所在",
    },
    {
        "location_id": "xiaoleiyinsi",
        "name": "小雷音寺",
        "full_name": "小雷音寺/Little Thunder Temple",
        "location_type": "寺院",
        "faction": "妖界",
        "region": "西牛贺洲",
        "danger_level": 5,
        "description": "黄眉老佛假冒佛祖之地，困住取经团队",
    },
    {
        "location_id": "tianzhu_guo",
        "name": "天竺国",
        "full_name": "天竺国/India",
        "location_type": "国度",
        "faction": "人间",
        "region": "西牛贺洲",
        "danger_level": 2,
        "description": "取经途中大国，玉兔精假扮公主之地",
    },
    {
        "location_id": "lingshan",
        "name": "灵山",
        "full_name": "灵山/Vulture Peak",
        "location_type": "圣地",
        "faction": "佛门",
        "region": "西牛贺洲",
        "danger_level": 0,
        "description": "如来佛祖讲法之所，取经终点",
    },
    {
        "location_id": "chang_an",
        "name": "长安",
        "full_name": "长安/Chang'an",
        "location_type": "都城",
        "faction": "人间",
        "region": "东土大唐",
        "danger_level": 0,
        "description": "大唐国都，取经起点",
    },
    {
        "location_id": "longgong",
        "name": "东海龙宫",
        "full_name": "东海龙宫/East Sea Dragon Palace",
        "location_type": "水府",
        "faction": "天庭",
        "region": "东海",
        "danger_level": 1,
        "description": "东海龙王敖广的宫殿，孙悟空取得金箍棒之处",
    },
    {
        "location_id": "tiangong",
        "name": "天宫",
        "full_name": "天宫/Heavenly Palace",
        "location_type": "仙宫",
        "faction": "天庭",
        "region": "三界之上",
        "danger_level": 0,
        "description": "玉帝治所，大闹天宫之地",
    },
    {
        "location_id": "difu",
        "name": "地府",
        "full_name": "地府/Underworld",
        "location_type": "冥府",
        "faction": "天庭",
        "region": "阴间",
        "danger_level": 3,
        "description": "十殿阎罗治所，孙悟空大闹地府销生死簿",
    },
    {
        "location_id": "wuzhuang_guan",
        "name": "五庄观",
        "full_name": "五庄观/Wuzhuang Temple",
        "location_type": "道观",
        "faction": "天庭",
        "region": "万寿山",
        "danger_level": 2,
        "description": "镇元大仙道场，有人参果树，孙悟空推倒后请观音复活",
    },
    {
        "location_id": "tongtian_he",
        "name": "通天河",
        "full_name": "通天河/Heavenly River",
        "location_type": "河流",
        "faction": "妖界",
        "region": "西牛贺洲",
        "danger_level": 3,
        "description": "灵感大王（金鱼精）作祟之处，取经团队两次渡河",
    },
    {
        "location_id": "shiziling",
        "name": "狮驼岭",
        "full_name": "狮驼岭/Lion Camel Ridge",
        "location_type": "山岭",
        "faction": "妖界",
        "region": "西牛贺洲",
        "danger_level": 5,
        "description": "青狮、白象、大鹏三大魔王盘踞之处，取经路上最凶险之地",
    },
    {
        "location_id": "pansidong",
        "name": "盘丝洞",
        "full_name": "盘丝洞/Silk Web Cave",
        "location_type": "洞府",
        "faction": "妖界",
        "region": "西牛贺洲",
        "danger_level": 3,
        "description": "七个蜘蛛精盘踞之处，濯垢泉洗澡被悟空发现",
    },
    {
        "location_id": "wuji_guo",
        "name": "乌鸡国",
        "full_name": "乌鸡国/Wuji Kingdom",
        "location_type": "国度",
        "faction": "人间",
        "region": "西牛贺洲",
        "danger_level": 2,
        "description": "妖道害死国王篡位，孙悟空识破并降妖",
    },
    {
        "location_id": "chechi_guo",
        "name": "车迟国",
        "full_name": "车迟国/Chechi Kingdom",
        "location_type": "国度",
        "faction": "人间",
        "region": "西牛贺洲",
        "danger_level": 2,
        "description": "三大仙（虎力、鹿力、羊力）掌权，与取经团队斗法",
    },
]
