"""西游记法术数据"""

SPELLS = [
    {
        "spell_id": "qihsi",
        "name": "七十二变",
        "full_name": "七十二变/72 Transformations",
        "spell_type": "变化",
        "master": "孙悟空",
        "origin": "菩提祖师",
        "power": "能变万物，飞禽走兽花草树木",
        "description": "孙悟空从须菩提祖师处习得，以躲避三灾利害",
    },
    {
        "spell_id": "jindouyun",
        "name": "筋斗云",
        "full_name": "筋斗云/Somersault Cloud",
        "spell_type": "遁术",
        "master": "孙悟空",
        "origin": "自悟",
        "power": "一个筋斗十万八千里",
        "description": "孙悟空独门纵云术，一个筋斗可达十万八千里",
    },
    {
        "spell_id": "huoyanjingjing",
        "name": "火眼金睛",
        "full_name": "火眼金睛/Fiery Golden Eyes",
        "spell_type": "神通",
        "master": "孙悟空",
        "origin": "八卦炉中炼出",
        "power": "能看透妖魔原形，识破一切幻化",
        "description": "孙悟空在太上老君八卦炉中炼出，能识破妖魔真身",
    },
    {
        "spell_id": "shenwaizhanshu",
        "name": "身外化身",
        "full_name": "身外化身/Body Outside Body",
        "spell_type": "变化",
        "master": "孙悟空",
        "origin": "自悟",
        "power": "拔毫毛变化千百个分身",
        "description": "孙悟空拔毫毛一吹，可变出千百个自己",
    },
    {
        "spell_id": "dunshenfa",
        "name": "定身法",
        "full_name": "定身法/Immobilization",
        "spell_type": "法术",
        "master": "孙悟空",
        "origin": "菩提祖师",
        "power": "用手指一点，人和物皆不能动",
        "description": "孙悟空的控场法术，一个'定'字可定住一切",
    },
    {
        "spell_id": "sansanchentian",
        "name": "三昧真火",
        "full_name": "三昧真火/Samadhi Fire",
        "spell_type": "神通",
        "master": "红孩儿",
        "origin": "自悟",
        "power": "神火之王，水不能灭",
        "description": "红孩儿独门神通，孙悟空被烧得痛不欲生",
    },
    {
        "spell_id": "bashanjue",
        "name": "芭蕉扇法",
        "full_name": "芭蕉扇法/Banana Fan Method",
        "spell_type": "法术",
        "master": "铁扇公主",
        "origin": "昆仑山",
        "power": "一扇生风二扇生雨三扇灭火",
        "description": "需口诀驱动，扇子可大可小，藏在口中",
    },
    {
        "spell_id": "jinjizhou",
        "name": "紧箍咒",
        "full_name": "紧箍咒/Tight-Fillet Incantation",
        "spell_type": "咒语",
        "master": "唐僧",
        "origin": "如来佛祖",
        "power": "念咒则金箍收紧，痛不可忍",
        "description": "如来赐观音传唐僧，用于约束孙悟空",
    },
    {
        "spell_id": "yanpengbailei",
        "name": "腾云驾雾",
        "full_name": "腾云驾雾/Cloud Traversal",
        "spell_type": "遁术",
        "master": "众神仙",
        "origin": "修为",
        "power": "能在云端飞行翱翔",
        "description": "神仙基本遁术，修为越高飞得越快越远",
    },
    {
        "spell_id": "huhuan_shu",
        "name": "呼风唤雨",
        "full_name": "呼风唤雨/Weather Control",
        "spell_type": "法术",
        "master": "四海龙王",
        "origin": "天职",
        "power": "能随意调节天气风雨雷电",
        "description": "四海龙王的天职神通，下雨须奉玉帝旨意",
    },
]
