"""西游记法宝数据"""

TREASURES = [
    {
        "treasure_id": "jingubang",
        "name": "金箍棒",
        "full_name": "金箍棒/Golden Cudgel",
        "treasure_type": "兵器",
        "holder": "孙悟空",
        "origin": "东海龙宫",
        "power": "重一万三千五百斤，可大可小",
        "description": "原为东海龙宫定海神针，被孙悟空取走为兵器",
    },
    {
        "treasure_id": "jiuchidingpa",
        "name": "九齿钉耙",
        "full_name": "九齿钉耙/Nine-Tooth Iron Rake",
        "treasure_type": "兵器",
        "holder": "猪八戒",
        "origin": "天庭（太上老君锻造）",
        "power": "全名上宝沁金钯，太上老君锻造",
        "description": "太上老君用神冰铁锻造，赐予天蓬元帅",
    },
    {
        "treasure_id": "bashanshan",
        "name": "芭蕉扇",
        "full_name": "芭蕉扇/Banana Leaf Fan",
        "treasure_type": "法宝",
        "holder": "铁扇公主",
        "origin": "昆仑山",
        "power": "能灭火焰山之火，一扇灭火二扇生风三扇降雨",
        "description": "昆仑山后自混沌开辟以来产成的灵宝，阴扇能灭火",
    },
    {
        "treasure_id": "zijingling",
        "name": "紫金铃",
        "full_name": "紫金铃/Purple Gold Bells",
        "treasure_type": "法宝",
        "holder": "观音菩萨坐骑金毛犼",
        "origin": "太上老君",
        "power": "晃一晃出火，晃两晃生烟，晃三晃飞沙走石",
        "description": "太上老君所炼，被金毛犼盗下凡间",
    },
    {
        "treasure_id": "renzhongdai",
        "name": "人种袋",
        "full_name": "人种袋/Human Seed Bag",
        "treasure_type": "法宝",
        "holder": "黄眉老佛",
        "origin": "弥勒佛",
        "power": "能收一切人神鬼怪",
        "description": "弥勒佛的宝贝，被童子盗下凡间",
    },
    {
        "treasure_id": "jinnang",
        "name": "金铙",
        "full_name": "金铙/Golden Cymbals",
        "treasure_type": "法宝",
        "holder": "黄眉老佛",
        "origin": "弥勒佛",
        "power": "合上后任你多大神通也出不来",
        "description": "弥勒佛的宝贝，困住孙悟空",
    },
    {
        "treasure_id": "zijinghulu",
        "name": "紫金红葫芦",
        "full_name": "紫金红葫芦/Purple Gold Gourd",
        "treasure_type": "法宝",
        "holder": "金角大王",
        "origin": "太上老君",
        "power": "叫人名若应声即被吸入，一时三刻化为脓水",
        "description": "太上老君炼丹之物，被童子盗下凡间",
    },
    {
        "treasure_id": "yangzhiyujingping",
        "name": "羊脂玉净瓶",
        "full_name": "羊脂玉净瓶/Jade Vase",
        "treasure_type": "法宝",
        "holder": "观音菩萨",
        "origin": "佛门",
        "power": "甘露水能起死回生，能灭火焰山之火",
        "description": "观音菩萨随身法宝，曾复活人参果树",
    },
    {
        "treasure_id": "jinguzhou",
        "name": "紧箍咒",
        "full_name": "紧箍咒/Tight-Fillet Spell",
        "treasure_type": "法器",
        "holder": "唐僧",
        "origin": "如来佛祖",
        "power": "念之则箍紧头痛欲裂",
        "description": "如来赐予观音转赠唐僧，用于约束孙悟空",
    },
    {
        "treasure_id": "xianglu",
        "name": "降妖宝杖",
        "full_name": "降妖宝杖/Demon-Subduing Staff",
        "treasure_type": "兵器",
        "holder": "沙僧",
        "origin": "天庭（鲁班锻造）",
        "power": "月宫梭罗仙木锻造",
        "description": "沙僧随身兵器，卷帘大将时所用",
    },
    {
        "treasure_id": "xiujiqiu",
        "name": "绣花针",
        "full_name": "绣花针/Embroidery Needle",
        "treasure_type": "法宝",
        "holder": "昴日星官",
        "origin": "天庭",
        "power": "专克蜈蚣精多目怪",
        "description": "昴日星官本相大公鸡，其绣花针克制蜈蚣精",
    },
    {
        "treasure_id": "biganjian",
        "name": "避火罩",
        "full_name": "避火罩/Fire-Proof Cover",
        "treasure_type": "法器",
        "holder": "广晋天王",
        "origin": "天庭",
        "power": "可避一切火灾",
        "description": "广晋天王借予悟空保护唐僧避火",
    },
]
