"""三国演义人物数据 — 精简版 ~33人，按势力分组"""

CHARACTERS = [
    # ── 魏 ──
    {
        "character_id": "cao_cao",
        "name": "曹操",
        "faction": "faction_wei",
        "title": "魏武帝",
        "role": "君主",
        "birth_year": 155,
        "death_year": 220,
        "origin": "沛国谯县",
        "description": "字孟德，小名阿瞒。挟天子以令诸侯，统一北方，文武兼备，一代枭雄。善用兵法，唯才是举，亦为建安文学领袖。",
    },
    {
        "character_id": "cao_pi",
        "name": "曹丕",
        "faction": "faction_wei",
        "title": "魏文帝",
        "role": "君主",
        "birth_year": 187,
        "death_year": 226,
        "origin": "沛国谯县",
        "description": "字子桓，曹操之子。代汉称帝建立曹魏，在位七年。著有《典论》，为文学批评开山之作。",
    },
    {
        "character_id": "xiahou_dun",
        "name": "夏侯惇",
        "faction": "faction_wei",
        "title": "大将军",
        "role": "武将",
        "birth_year": None,
        "death_year": 220,
        "origin": "沛国谯县",
        "description": "字元让，曹操从弟。拔矢啖睛，勇猛刚烈，为曹魏宗族大将之首。",
    },
    {
        "character_id": "xiahou_yuan",
        "name": "夏侯渊",
        "faction": "faction_wei",
        "title": "征西将军",
        "role": "武将",
        "birth_year": None,
        "death_year": 219,
        "origin": "沛国谯县",
        "description": "字妙才，夏侯惇族弟。善千里奔袭，镇守汉中时被黄忠斩于定军山。",
    },
    {
        "character_id": "zhang_liao",
        "name": "张辽",
        "faction": "faction_wei",
        "title": "征东将军",
        "role": "武将",
        "birth_year": 169,
        "death_year": 222,
        "origin": "雁门马邑",
        "description": "字文远，原属吕布，后归曹操。合肥之战率八百人破孙权十万大军，威震逍遥津。",
    },
    {
        "character_id": "xu_chu",
        "name": "许褚",
        "faction": "faction_wei",
        "title": "武卫将军",
        "role": "武将",
        "birth_year": None,
        "death_year": None,
        "origin": "谯国谯县",
        "description": "字仲康，号'虎痴'。力大无穷，忠心护主，为曹操贴身护卫。",
    },
    {
        "character_id": "sima_yi",
        "name": "司马懿",
        "faction": "faction_wei",
        "title": "太傅",
        "role": "谋士",
        "birth_year": 179,
        "death_year": 251,
        "origin": "河内温县",
        "description": "字仲达，深谋远虑，隐忍不发。与诸葛亮对峙多年，发动高平陵之变夺取曹魏大权，为晋朝奠基人。",
    },
    {
        "character_id": "guo_jia",
        "name": "郭嘉",
        "faction": "faction_wei",
        "title": "军师祭酒",
        "role": "谋士",
        "birth_year": 170,
        "death_year": 207,
        "origin": "颍川阳翟",
        "description": "字奉孝，曹操首席谋士。算无遗策，遗计定辽东，英年早逝，曹操叹'哀哉奉孝'。",
    },
    # ── 蜀 ──
    {
        "character_id": "liu_bei",
        "name": "刘备",
        "faction": "faction_shu",
        "title": "汉昭烈帝",
        "role": "君主",
        "birth_year": 161,
        "death_year": 223,
        "origin": "涿郡涿县",
        "description": "字玄德，汉室宗亲。桃园结义，三顾茅庐，以仁义著称。建立蜀汉，白帝城托孤后病逝。",
    },
    {
        "character_id": "guan_yu",
        "name": "关羽",
        "faction": "faction_shu",
        "title": "前将军",
        "role": "武将",
        "birth_year": None,
        "death_year": 220,
        "origin": "河东解县",
        "description": "字云长，五虎上将之首。温酒斩华雄，过五关斩六将，水淹七军威震华夏，后败走麦城被杀。忠义化身，后世封'武圣'。",
    },
    {
        "character_id": "zhang_fei",
        "name": "张飞",
        "faction": "faction_shu",
        "title": "车骑将军",
        "role": "武将",
        "birth_year": None,
        "death_year": 221,
        "origin": "涿郡",
        "description": "字翼德，与刘备关羽桃园结义。长坂坡据水断桥，义释严颜，勇猛粗中有细。",
    },
    {
        "character_id": "zhuge_liang",
        "name": "诸葛亮",
        "faction": "faction_shu",
        "title": "丞相",
        "role": "谋士",
        "birth_year": 181,
        "death_year": 234,
        "origin": "琅琊阳都",
        "description": "字孔明，号卧龙。隆中对规划三分天下，辅佐刘备建立蜀汉。六出祁山北伐中原，鞠躬尽瘁死而后已。",
    },
    {
        "character_id": "zhao_yun",
        "name": "赵云",
        "faction": "faction_shu",
        "title": "镇军将军",
        "role": "武将",
        "birth_year": None,
        "death_year": 229,
        "origin": "常山真定",
        "description": "字子龙，五虎上将之一。长坂坡单骑救主，截江夺阿斗，一身是胆，忠勇无双。",
    },
    {
        "character_id": "ma_chao",
        "name": "马超",
        "faction": "faction_shu",
        "title": "骠骑将军",
        "role": "武将",
        "birth_year": 176,
        "death_year": 222,
        "origin": "扶风茂陵",
        "description": "字孟起，五虎上将之一。西凉锦马超，杀得曹操割须弃袍，后归刘备。",
    },
    {
        "character_id": "huang_zhong",
        "name": "黄忠",
        "faction": "faction_shu",
        "title": "后将军",
        "role": "武将",
        "birth_year": None,
        "death_year": 220,
        "origin": "南阳",
        "description": "字汉升，五虎上将之一。老当益壮，定军山斩夏侯渊，勇冠三军。",
    },
    {
        "character_id": "wei_yan",
        "name": "魏延",
        "faction": "faction_shu",
        "title": "征西大将军",
        "role": "武将",
        "birth_year": None,
        "death_year": 234,
        "origin": "义阳",
        "description": "字文长，勇猛过人但性格孤傲。屡立战功，诸葛亮死后因'反叛'被马岱所杀。",
    },
    {
        "character_id": "jiang_wei",
        "name": "姜维",
        "faction": "faction_shu",
        "title": "大将军",
        "role": "武将",
        "birth_year": 202,
        "death_year": 264,
        "origin": "天水冀县",
        "description": "字伯约，诸葛亮衣钵传人。九伐中原，蜀亡后假降图复国，事败殉国。",
    },
    {
        "character_id": "pang_tong",
        "name": "庞统",
        "faction": "faction_shu",
        "title": "军师中郎将",
        "role": "谋士",
        "birth_year": 179,
        "death_year": 214,
        "origin": "襄阳",
        "description": "字士元，号凤雏。与诸葛亮齐名，'卧龙凤雏得一可安天下'。落凤坡中箭身亡。",
    },
    # ── 吴 ──
    {
        "character_id": "sun_jian",
        "name": "孙坚",
        "faction": "faction_wu",
        "title": "破虏将军",
        "role": "君主",
        "birth_year": 155,
        "death_year": 192,
        "origin": "吴郡富春",
        "description": "字文台，东吴基业开创者。江东猛虎，讨董先锋，跨江击刘表时中伏身亡。",
    },
    {
        "character_id": "sun_ce",
        "name": "孙策",
        "faction": "faction_wu",
        "title": "讨逆将军",
        "role": "君主",
        "birth_year": 175,
        "death_year": 200,
        "origin": "吴郡富春",
        "description": "字伯符，小霸王。以玉玺借兵，横扫江东六郡，奠定东吴基业，遇刺身亡时年仅二十六。",
    },
    {
        "character_id": "sun_quan",
        "name": "孙权",
        "faction": "faction_wu",
        "title": "吴大帝",
        "role": "君主",
        "birth_year": 182,
        "death_year": 252,
        "origin": "吴郡富春",
        "description": "字仲谋，承父兄之业据守江东。联刘抗曹于赤壁，后称帝建吴。'生子当如孙仲谋'。",
    },
    {
        "character_id": "zhou_yu",
        "name": "周瑜",
        "faction": "faction_wu",
        "title": "大都督",
        "role": "谋士",
        "birth_year": 175,
        "death_year": 210,
        "origin": "庐江舒县",
        "description": "字公瑾，东吴首席统帅。赤壁之战统军破曹，文武双全，英年早逝，'既生瑜何生亮'。",
    },
    {
        "character_id": "lu_xun",
        "name": "陆逊",
        "faction": "faction_wu",
        "title": "上大将军",
        "role": "谋士",
        "birth_year": 183,
        "death_year": 245,
        "origin": "吴郡吴县",
        "description": "字伯言，夷陵之战火烧连营大败刘备，后任丞相，为东吴柱石。",
    },
    {
        "character_id": "lu_meng",
        "name": "吕蒙",
        "faction": "faction_wu",
        "title": "大都督",
        "role": "武将",
        "birth_year": 178,
        "death_year": 220,
        "origin": "汝南富陂",
        "description": "字子明，'吴下阿蒙'到'刮目相看'。白衣渡江袭取荆州，擒杀关羽。",
    },
    {
        "character_id": "gan_ning",
        "name": "甘宁",
        "faction": "faction_wu",
        "title": "西陵太守",
        "role": "武将",
        "birth_year": None,
        "death_year": None,
        "origin": "巴郡临江",
        "description": "字兴霸，原为水贼，号'锦帆贼'。百骑劫魏营，勇猛善战，为东吴猛将。",
    },
    {
        "character_id": "huang_gai",
        "name": "黄盖",
        "faction": "faction_wu",
        "title": "武锋中郎将",
        "role": "武将",
        "birth_year": None,
        "death_year": None,
        "origin": "零陵泉陵",
        "description": "字公覆，赤壁之战献苦肉计，火烧曹营，老将建功。",
    },
    # ── 群雄 ──
    {
        "character_id": "dong_zhuo",
        "name": "董卓",
        "faction": "faction_qunxiong",
        "title": "太师",
        "role": "诸侯",
        "birth_year": None,
        "death_year": 192,
        "origin": "陇西临洮",
        "description": "字仲颖，率西凉军入京把持朝政，废立皇帝，残暴无道，被司徒王允设计诛杀。",
    },
    {
        "character_id": "lu_bu",
        "name": "吕布",
        "faction": "faction_qunxiong",
        "title": "温侯",
        "role": "武将",
        "birth_year": None,
        "death_year": 198,
        "origin": "五原郡九原",
        "description": "字奉先，天下第一猛将。'人中吕布，马中赤兔'。三姓家奴，反复无常，下邳兵败被曹操所杀。",
    },
    {
        "character_id": "yuan_shao",
        "name": "袁绍",
        "faction": "faction_qunxiong",
        "title": "大将军",
        "role": "诸侯",
        "birth_year": None,
        "death_year": 202,
        "origin": "汝南汝阳",
        "description": "字本初，四世三公，门生故吏遍天下。讨董盟主，官渡之战败于曹操，忧愤而亡。",
    },
    {
        "character_id": "yuan_shu",
        "name": "袁术",
        "faction": "faction_qunxiong",
        "title": "仲家帝",
        "role": "诸侯",
        "birth_year": None,
        "death_year": 199,
        "origin": "汝南汝阳",
        "description": "字公路，袁绍之弟。据淮南称帝，众叛亲离，呕血而亡。",
    },
    {
        "character_id": "liu_biao",
        "name": "刘表",
        "faction": "faction_qunxiong",
        "title": "荆州牧",
        "role": "诸侯",
        "birth_year": None,
        "death_year": 208,
        "origin": "山阳高平",
        "description": "字景升，汉室宗亲。坐拥荆州九郡，优柔寡断，死后荆州归曹操。",
    },
    {
        "character_id": "zhang_jiao",
        "name": "张角",
        "faction": "faction_qunxiong",
        "title": "天公将军",
        "role": "首领",
        "birth_year": None,
        "death_year": 184,
        "origin": "巨鹿",
        "description": "创立太平道，发动黄巾起义，自称'天公将军'。起义同年病逝，黄巾军随即瓦解。",
    },
    {
        "character_id": "gongsun_zan",
        "name": "公孙瓒",
        "faction": "faction_qunxiong",
        "title": "前将军",
        "role": "诸侯",
        "birth_year": None,
        "death_year": 199,
        "origin": "辽西令支",
        "description": "字伯珪，白马将军，据幽州。与袁绍争冀州失败，自焚而亡。",
    },
    # ── 晋 ──
    {
        "character_id": "sima_zhao",
        "name": "司马昭",
        "faction": "faction_jin",
        "title": "晋王",
        "role": "君主",
        "birth_year": 211,
        "death_year": 265,
        "origin": "河内温县",
        "description": "字子上，司马懿之子。'司马昭之心路人皆知'，灭蜀后进封晋王，为西晋代魏奠基。",
    },
]


def get_character(character_id: str) -> dict | None:
    """根据 character_id 获取人物信息"""
    for char in CHARACTERS:
        if char["character_id"] == character_id:
            return char
    return None


def get_character_by_name(name: str) -> dict | None:
    """根据人物姓名获取人物信息"""
    for char in CHARACTERS:
        if char["name"] == name:
            return char
    return None


def search_characters(keyword: str) -> list[dict]:
    """根据关键字搜索人物（匹配姓名、字、描述）"""
    results = []
    for char in CHARACTERS:
        if (
            keyword in char["name"]
            or keyword in char.get("description", "")
            or keyword in char.get("title", "")
            or keyword in char.get("origin", "")
        ):
            results.append(char)
    return results
