"""三国演义事件数据 — ~40个关键事件，覆盖6个时间锚点"""

EVENTS = [
    # ── 184年：乱世开端 ──
    {
        "event_id": "event_huangjin_qiyi",
        "name": "黄巾起义",
        "year": 184,
        "month": None,
        "category": "政治",
        "location": "luoyang",
        "participants": ["zhang_jiao"],
        "mentioned_characters": ["cao_cao", "liu_bei", "guan_yu", "zhang_fei"],
        "description": "张角率太平道信徒发动起义，头裹黄巾为号。天下响应，州郡失守，汉室威信尽失，群雄趁机起兵。",
    },
    {
        "event_id": "event_taoyuan_jieyi",
        "name": "桃园结义",
        "year": 184,
        "month": None,
        "category": "联盟",
        "location": "youzhou",
        "participants": ["liu_bei", "guan_yu", "zhang_fei"],
        "mentioned_characters": [],
        "description": "刘备、关羽、张飞于涿郡桃园结为异姓兄弟，誓同生死。'不求同年同月同日生，但求同年同月同日死'。",
    },
    # ── 189年 ──
    {
        "event_id": "event_dong_zhuo_luan_zheng",
        "name": "董卓乱政",
        "year": 189,
        "month": None,
        "category": "政治",
        "location": "luoyang",
        "participants": ["dong_zhuo", "lu_bu"],
        "mentioned_characters": ["cao_cao"],
        "description": "董卓率西凉军入京，废少帝立献帝，自封太师把持朝政。残暴无道，焚洛阳迁长安，天下共愤。",
    },
    # ── 190年：群雄割据 ──
    {
        "event_id": "event_taodong_lianmeng",
        "name": "讨董联盟",
        "year": 190,
        "month": None,
        "category": "联盟",
        "location": "luoyang",
        "participants": ["yuan_shao", "cao_cao"],
        "mentioned_characters": ["liu_bei", "guan_yu", "zhang_fei", "dong_zhuo"],
        "description": "十八路诸侯推袁绍为盟主，联合讨伐董卓。各怀心思，迟疑不前，唯曹操孤军追击败于荥阳。",
    },
    {
        "event_id": "event_hulao_guan_zhizhan",
        "name": "虎牢关之战",
        "year": 190,
        "month": None,
        "category": "战役",
        "location": "hulao_pass",
        "participants": ["liu_bei", "guan_yu", "zhang_fei", "lu_bu"],
        "mentioned_characters": ["dong_zhuo", "yuan_shao"],
        "description": "三英战吕布，刘关张三兄弟合力战退天下第一猛将吕布，虎牢关一战成名。",
    },
    # ── 192年 ──
    {
        "event_id": "event_sunjian_zhan_siyang",
        "name": "孙坚跨江击刘表",
        "year": 192,
        "month": None,
        "category": "战役",
        "location": "jingzhou",
        "participants": ["sun_jian"],
        "mentioned_characters": ["sun_ce", "sun_quan"],
        "description": "孙坚跨江击刘表，中黄祖部将吕公埋伏，中石身亡。江东猛虎就此陨落。",
    },
    {
        "event_id": "event_wangyun_lianhuan_ji",
        "name": "王允连环计",
        "year": 192,
        "month": None,
        "category": "计谋",
        "location": "changan",
        "participants": ["dong_zhuo", "lu_bu"],
        "mentioned_characters": [],
        "description": "司徒王允以貂蝉设连环计，离间董卓吕布。吕布杀董卓，然王允亦未能安抚西凉军，终被李傕郭汜所杀。",
    },
    # ── 194年 ──
    {
        "event_id": "event_cao_cao_yanzhou",
        "name": "曹操入兖州",
        "year": 194,
        "month": None,
        "category": "政治",
        "location": "yanzhou",
        "participants": ["cao_cao"],
        "mentioned_characters": [],
        "description": "曹操入兖州破黄巾，收编青州兵三十余万，以此为基业开始逐鹿中原。",
    },
    {
        "event_id": "event_taoqian_rang_xuzhou",
        "name": "陶谦让徐州",
        "year": 194,
        "month": None,
        "category": "政治",
        "location": "xuzhou",
        "participants": ["liu_bei"],
        "mentioned_characters": ["cao_cao"],
        "description": "徐州牧陶谦三让徐州于刘备，刘备始有立足之地。然徐州四战之地，难以久守。",
    },
    # ── 196年 ──
    {
        "event_id": "event_cao_cao_ying_xian_di",
        "name": "曹操迎献帝",
        "year": 196,
        "month": None,
        "category": "政治",
        "location": "xuchang",
        "participants": ["cao_cao"],
        "mentioned_characters": [],
        "description": "曹操迎汉献帝至许昌，'挟天子以令诸侯'，取得政治上的正统地位，势力大增。",
    },
    # ── 198年 ──
    {
        "event_id": "event_lu_bu_miewang",
        "name": "吕布灭亡",
        "year": 198,
        "month": None,
        "category": "战役",
        "location": "xuzhou",
        "participants": ["cao_cao", "lu_bu"],
        "mentioned_characters": ["liu_bei"],
        "description": "曹操围攻下邳，吕布部将叛变献城。吕布被擒后处死，'人中吕布'就此落幕。",
    },
    {
        "event_id": "event_yuanshu_chengdi",
        "name": "袁术称帝",
        "year": 197,
        "month": None,
        "category": "政治",
        "location": "shouchun",
        "participants": ["yuan_shu"],
        "mentioned_characters": ["yuan_shao"],
        "description": "袁术据寿春称帝，国号仲家。然众叛亲离，遭各路诸侯讨伐，呕血而亡。",
    },
    # ── 200年：北方统一 ──
    {
        "event_id": "event_guandu_zhizhan",
        "name": "官渡之战",
        "year": 200,
        "month": None,
        "category": "战役",
        "location": "guandu",
        "participants": ["cao_cao", "yuan_shao"],
        "mentioned_characters": ["guo_jia", "xu_chu"],
        "description": "曹操以少胜多大败袁绍，火烧乌巢粮草。此战奠定曹操统一北方的基础，为三国最著名的以弱胜强战役之一。",
    },
    {
        "event_id": "event_sunce_ping_jiangdong",
        "name": "孙策平定江东",
        "year": 200,
        "month": None,
        "category": "政治",
        "location": "jianye",
        "participants": ["sun_ce", "zhou_yu"],
        "mentioned_characters": ["sun_quan"],
        "description": "孙策以玉玺向袁术借兵，与周瑜横扫江东六郡，奠定东吴基业。人称'小霸王'。",
    },
    # ── 207年 ──
    {
        "event_id": "event_longzhong_dui",
        "name": "隆中对",
        "year": 207,
        "month": None,
        "category": "计谋",
        "location": "nanyang",
        "participants": ["liu_bei", "zhuge_liang"],
        "mentioned_characters": ["cao_cao", "sun_quan"],
        "description": "刘备三顾茅庐，诸葛亮提出'隆中对'战略：跨有荆益，联吴抗曹，待机北伐，三分天下。",
    },
    # ── 208年：三分天下 ──
    {
        "event_id": "event_chibi_zhizhan",
        "name": "赤壁之战",
        "year": 208,
        "month": None,
        "category": "战役",
        "location": "chibi",
        "participants": ["cao_cao", "zhou_yu", "zhuge_liang", "huang_gai"],
        "mentioned_characters": ["sun_quan", "liu_bei", "lu_meng"],
        "description": "孙刘联军以火攻大破曹操八十万大军，奠定三分天下格局。黄盖苦肉计、草船借箭、借东风皆出于此。",
    },
    {
        "event_id": "event_changbanpo_zhizhan",
        "name": "长坂坡之战",
        "year": 208,
        "month": None,
        "category": "战役",
        "location": "changbanpo",
        "participants": ["liu_bei", "zhao_yun", "zhang_fei"],
        "mentioned_characters": ["cao_cao"],
        "description": "曹操追击刘备于长坂坡，赵云单骑救阿斗，张飞据水断桥。刘备惨败但核心团队犹存。",
    },
    # ── 211年 ──
    {
        "event_id": "event_liu_bei_ru_shu",
        "name": "刘备入蜀",
        "year": 211,
        "month": None,
        "category": "政治",
        "location": "chengdu",
        "participants": ["liu_bei", "zhuge_liang", "pang_tong"],
        "mentioned_characters": [],
        "description": "刘备应刘璋之邀入蜀，名为助守实为取蜀。庞统献上中下三计，落凤坡中箭身亡。",
    },
    {
        "event_id": "event_machao_zhan_cao_cao",
        "name": "马超战曹操",
        "year": 211,
        "month": None,
        "category": "战役",
        "location": "changan",
        "participants": ["ma_chao", "cao_cao"],
        "mentioned_characters": ["xu_chu"],
        "description": "马超为报父仇起兵反曹，杀得曹操割须弃袍。许褚裸衣斗马超，后曹操用反间计离间马超韩遂。",
    },
    # ── 214年 ──
    {
        "event_id": "event_liu_bei_qu_yizhou",
        "name": "刘备取益州",
        "year": 214,
        "month": None,
        "category": "政治",
        "location": "chengdu",
        "participants": ["liu_bei", "zhuge_liang"],
        "mentioned_characters": ["pang_tong", "zhao_yun"],
        "description": "刘备攻取成都，刘璋投降。刘备自领益州牧，终于有了立足之地，实现隆中对'跨有荆益'的第一步。",
    },
    {
        "event_id": "event_pangtong_luofengpo",
        "name": "庞统落凤坡",
        "year": 214,
        "month": None,
        "category": "战役",
        "location": "chengdu",
        "participants": ["pang_tong"],
        "mentioned_characters": ["liu_bei", "zhuge_liang"],
        "description": "庞统随刘备入蜀，于落凤坡中张任埋伏，中箭身亡。'卧龙凤雏得一可安天下'，凤雏就此陨落。",
    },
    # ── 215年 ──
    {
        "event_id": "event_hanzhong_zhizhan",
        "name": "汉中之战",
        "year": 215,
        "month": None,
        "category": "战役",
        "location": "hanzhong",
        "participants": ["liu_bei", "cao_cao", "huang_zhong", "zhao_yun"],
        "mentioned_characters": ["xiahou_yuan", "zhuge_liang"],
        "description": "刘备与曹操争夺汉中，黄忠定军山斩夏侯渊，赵云汉水空营退敌。刘备取汉中后进位汉中王。",
    },
    {
        "event_id": "event_hefei_zhizhan",
        "name": "合肥之战",
        "year": 215,
        "month": None,
        "category": "战役",
        "location": "hefei",
        "participants": ["zhang_liao", "sun_quan"],
        "mentioned_characters": ["gan_ning"],
        "description": "张辽率八百勇士突袭孙权十万大军，威震逍遥津。孙权险些被擒，'张辽止啼'传为佳话。",
    },
    # ── 219年 ──
    {
        "event_id": "event_guan_yu_shui_yan_qi_jun",
        "name": "关羽水淹七军",
        "year": 219,
        "month": None,
        "category": "战役",
        "location": "xiangyang",
        "participants": ["guan_yu"],
        "mentioned_characters": ["cao_cao", "lu_meng"],
        "description": "关羽北伐襄樊，借汉水泛滥淹于禁七军，擒于禁斩庞德，威震华夏。然后方空虚，东吴吕蒙白衣渡江袭取荆州。",
    },
    # ── 220年：三国鼎立 ──
    {
        "event_id": "event_caopi_daihan",
        "name": "曹丕代汉",
        "year": 220,
        "month": None,
        "category": "政治",
        "location": "luoyang",
        "participants": ["cao_pi"],
        "mentioned_characters": ["cao_cao"],
        "description": "曹操病逝，曹丕逼汉献帝禅让，建立曹魏，东汉灭亡。四百年大汉就此终结。",
    },
    {
        "event_id": "event_guan_yu_bai_zou_maicheng",
        "name": "关羽败走麦城",
        "year": 220,
        "month": None,
        "category": "战役",
        "location": "jingzhou",
        "participants": ["guan_yu", "lu_meng"],
        "mentioned_characters": ["liu_bei", "sun_quan"],
        "description": "吕蒙白衣渡江袭取荆州，关羽腹背受敌，败走麦城被擒遇害。蜀汉失荆州，隆中对战略受挫。",
    },
    # ── 221年 ──
    {
        "event_id": "event_liu_bei_chengdi",
        "name": "刘备称帝",
        "year": 221,
        "month": None,
        "category": "政治",
        "location": "chengdu",
        "participants": ["liu_bei"],
        "mentioned_characters": ["zhuge_liang"],
        "description": "刘备在成都称帝，国号汉，史称蜀汉，以续汉统。随即兴兵伐吴为关羽报仇。",
    },
    # ── 222年 ──
    {
        "event_id": "event_yiling_zhizhan",
        "name": "夷陵之战",
        "year": 222,
        "month": None,
        "category": "战役",
        "location": "yiling",
        "participants": ["liu_bei", "lu_xun"],
        "mentioned_characters": ["zhuge_liang", "zhao_yun"],
        "description": "刘备兴兵伐吴，陆逊以逸待劳，火烧连营七百里。刘备大败退守白帝城，蜀汉元气大伤。",
    },
    # ── 223年 ──
    {
        "event_id": "event_liu_bei_tuo_gu",
        "name": "刘备托孤白帝城",
        "year": 223,
        "month": None,
        "category": "政治",
        "location": "bai_di_cheng",
        "participants": ["liu_bei", "zhuge_liang"],
        "mentioned_characters": [],
        "description": "刘备病危，于白帝城托孤诸葛亮：'若嗣子可辅则辅之，如其不才，君可自取。'诸葛亮涕泣受命。",
    },
    # ── 225年 ──
    {
        "event_id": "event_zhuge_qi_qin_meng_huo",
        "name": "诸葛亮七擒孟获",
        "year": 225,
        "month": None,
        "category": "计谋",
        "location": "chengdu",
        "participants": ["zhuge_liang"],
        "mentioned_characters": [],
        "description": "诸葛亮南征，七擒七纵孟获，攻心为上。南中平定，解除北伐后顾之忧。",
    },
    # ── 228年 ──
    {
        "event_id": "event_zhuge_bei_fa",
        "name": "诸葛亮北伐",
        "year": 228,
        "month": None,
        "category": "战役",
        "location": "hanzhong",
        "participants": ["zhuge_liang", "sima_yi", "wei_yan"],
        "mentioned_characters": ["zhao_yun", "ma_chao"],
        "description": "诸葛亮六出祁山北伐中原，以攻代守。虽有关键胜绩，终因粮草不济、国力悬殊未能成功。",
    },
    {
        "event_id": "event_shouchun_zhizhan",
        "name": "寿春之战",
        "year": 228,
        "month": None,
        "category": "战役",
        "location": "shouchun",
        "participants": [],
        "mentioned_characters": [],
        "description": "诸葛亮北伐期间，魏吴亦在寿春一带反复争夺。淮南地区为魏吴交锋前线。",
    },
    # ── 229年 ──
    {
        "event_id": "event_sun_quan_chengdi",
        "name": "孙权称帝",
        "year": 229,
        "month": None,
        "category": "政治",
        "location": "jianye",
        "participants": ["sun_quan"],
        "mentioned_characters": ["zhou_yu", "lu_xun"],
        "description": "孙权在建业称帝，国号吴，三国正式鼎立。东吴据江东六郡，凭长江天险与魏蜀分庭抗礼。",
    },
    # ── 234年 ──
    {
        "event_id": "event_zhuge_bing_shi_wuzhangyuan",
        "name": "诸葛亮病逝五丈原",
        "year": 234,
        "month": None,
        "category": "政治",
        "location": "wuzhangyuan",
        "participants": ["zhuge_liang", "sima_yi"],
        "mentioned_characters": ["jiang_wei"],
        "description": "诸葛亮第六次北伐，与司马懿对峙五丈原。积劳成疾，星落秋风五丈原，遗命退军。'鞠躬尽瘁，死而后已'。",
    },
    # ── 249年 ──
    {
        "event_id": "event_simayi_zheng_bian",
        "name": "高平陵之变",
        "year": 249,
        "month": None,
        "category": "政治",
        "location": "luoyang",
        "participants": ["sima_yi"],
        "mentioned_characters": ["cao_cao"],
        "description": "司马懿趁曹爽陪幼帝扫墓之机发动政变，控制洛阳，诛杀曹爽一族。曹魏实权落入司马氏手中。",
    },
    # ── 263年：统一归晋 ──
    {
        "event_id": "event_shu_han_miewang",
        "name": "蜀汉灭亡",
        "year": 263,
        "month": None,
        "category": "战役",
        "location": "chengdu",
        "participants": ["jiang_wei", "sima_zhao"],
        "mentioned_characters": ["zhuge_liang", "liu_bei"],
        "description": "司马昭遣钟会邓艾伐蜀，邓艾偷渡阴平直取成都，后主刘禅出降。蜀汉立国四十三年而亡。",
    },
    # ── 264年 ──
    {
        "event_id": "event_jiang_wei_zhong_yong",
        "name": "姜维殉国",
        "year": 264,
        "month": None,
        "category": "战役",
        "location": "chengdu",
        "participants": ["jiang_wei"],
        "mentioned_characters": ["zhuge_liang"],
        "description": "蜀亡后姜维假降钟会，策动钟会反魏图谋复国，事败被杀。'我计不成，乃天命也'。",
    },
    # ── 265年 ──
    {
        "event_id": "event_simayan_dai_wei",
        "name": "司马炎代魏",
        "year": 265,
        "month": None,
        "category": "政治",
        "location": "luoyang",
        "participants": [],
        "mentioned_characters": ["sima_yi", "sima_zhao"],
        "description": "司马炎逼魏帝曹奂禅让，建立西晋。曹魏立国四十六年而亡，历史重演禅让旧戏。",
    },
    # ── 280年 ──
    {
        "event_id": "event_xi_jin_mie_wu",
        "name": "西晋灭吴",
        "year": 280,
        "month": None,
        "category": "战役",
        "location": "jianye",
        "participants": [],
        "mentioned_characters": ["sun_quan"],
        "description": "西晋六路大军伐吴，王濬楼船下益州，直取建业。吴主孙皓出降，东吴灭亡，天下归晋，三国终局。",
    },
    {
        "event_id": "event_liu_biao_bing_shi",
        "name": "刘表病逝",
        "year": 208,
        "month": None,
        "category": "政治",
        "location": "xiangyang",
        "participants": ["liu_biao"],
        "mentioned_characters": ["liu_bei", "cao_cao"],
        "description": "荆州牧刘表病逝，次子刘琮降曹操。刘备失荆州依托，被迫南撤，引发长坂坡之战。",
    },
]


def get_event(event_id: str) -> dict | None:
    """根据 event_id 获取事件信息"""
    for event in EVENTS:
        if event["event_id"] == event_id:
            return event
    return None


def get_events_in_range(start: int, end: int) -> list[dict]:
    """获取指定年份范围内的事件"""
    return [e for e in EVENTS if start <= e["year"] <= end]
