"""三国演义地点数据 — ~30个关键地点"""

LOCATIONS = [
    {
        "location_id": "luoyang",
        "name": "洛阳",
        "faction": "faction_wei",
        "region": "司隶",
        "type": "城",
        "modern_location": "河南省洛阳市",
        "description": "东汉都城，董卓焚洛阳迁长安，后曹魏定都于此。天下之中，四战之地。",
    },
    {
        "location_id": "changan",
        "name": "长安",
        "faction": None,
        "region": "关中",
        "type": "城",
        "modern_location": "陕西省西安市",
        "description": "西汉故都，董卓挟献帝迁都于此。关中要地，八百里秦川。",
    },
    {
        "location_id": "xuchang",
        "name": "许昌",
        "faction": "faction_wei",
        "region": "豫州",
        "type": "城",
        "modern_location": "河南省许昌市",
        "description": "曹操迎献帝定都于此，'挟天子以令诸侯'的政治中心。",
    },
    {
        "location_id": "ye",
        "name": "邺城",
        "faction": "faction_wei",
        "region": "冀州",
        "type": "城",
        "modern_location": "河北省临漳县",
        "description": "袁绍旧都，曹操破袁后以此为北方重镇。铜雀台所在。",
    },
    {
        "location_id": "chengdu",
        "name": "成都",
        "faction": "faction_shu",
        "region": "益州",
        "type": "城",
        "modern_location": "四川省成都市",
        "description": "蜀汉都城，天府之国。刘备取益州后定都于此，诸葛亮治蜀中心。",
    },
    {
        "location_id": "jianye",
        "name": "建业",
        "faction": "faction_wu",
        "region": "扬州",
        "type": "城",
        "modern_location": "江苏省南京市",
        "description": "东吴都城，孙权建都于此。虎踞龙盘，长江天险。",
    },
    {
        "location_id": "jingzhou",
        "name": "荆州",
        "faction": None,
        "region": "荆州",
        "type": "州",
        "modern_location": "湖北省荆州市",
        "description": "兵家必争之地，刘表旧治。赤壁后三分荆州，关羽大意失荆州为蜀汉转折点。",
    },
    {
        "location_id": "xiangyang",
        "name": "襄阳",
        "faction": None,
        "region": "荆州",
        "type": "城",
        "modern_location": "湖北省襄阳市",
        "description": "荆州重镇，刘表治所。南北要冲，铁打的襄阳。",
    },
    {
        "location_id": "hanzhong",
        "name": "汉中",
        "faction": "faction_shu",
        "region": "益州",
        "type": "郡",
        "modern_location": "陕西省汉中市",
        "description": "蜀汉门户，入蜀咽喉。刘备取汉中后称汉中王，诸葛亮北伐以此为基地。",
    },
    {
        "location_id": "chibi",
        "name": "赤壁",
        "faction": "faction_wu",
        "region": "荆州",
        "type": "城",
        "modern_location": "湖北省赤壁市",
        "description": "赤壁之战发生地，孙刘联军火烧曹营，奠定三分天下格局。",
    },
    {
        "location_id": "guandu",
        "name": "官渡",
        "faction": "faction_wei",
        "region": "豫州",
        "type": "城",
        "modern_location": "河南省中牟县",
        "description": "官渡之战发生地，曹操以少胜多大败袁绍，统一北方关键之战。",
    },
    {
        "location_id": "yiling",
        "name": "夷陵",
        "faction": "faction_wu",
        "region": "荆州",
        "type": "城",
        "modern_location": "湖北省宜昌市",
        "description": "夷陵之战发生地，陆逊火烧连营大败刘备，蜀汉由盛转衰。",
    },
    {
        "location_id": "nanyang",
        "name": "南阳",
        "faction": None,
        "region": "荆州",
        "type": "郡",
        "modern_location": "河南省南阳市",
        "description": "诸葛亮躬耕之地，'臣本布衣，躬耕于南阳'。光武帝刘秀发迹之地。",
    },
    {
        "location_id": "jiangxia",
        "name": "江夏",
        "faction": "faction_wu",
        "region": "荆州",
        "type": "郡",
        "modern_location": "湖北省武汉市",
        "description": "荆州东部门户，赤壁之战前孙刘联盟的重要据点。",
    },
    {
        "location_id": "changsha",
        "name": "长沙",
        "faction": "faction_wu",
        "region": "荆州",
        "type": "郡",
        "modern_location": "湖南省长沙市",
        "description": "荆州南部重镇，黄忠、魏延旧治。关羽取长沙收黄忠魏延。",
    },
    {
        "location_id": "hefei",
        "name": "合肥",
        "faction": "faction_wei",
        "region": "扬州",
        "type": "城",
        "modern_location": "安徽省合肥市",
        "description": "曹魏东线重镇，张辽威震逍遥津之地。魏吴反复争夺的焦点。",
    },
    {
        "location_id": "shouchun",
        "name": "寿春",
        "faction": "faction_wei",
        "region": "扬州",
        "type": "城",
        "modern_location": "安徽省寿县",
        "description": "袁术称帝之地，淮南重镇。三国时期多次战役发生于此。",
    },
    {
        "location_id": "xuzhou",
        "name": "徐州",
        "faction": None,
        "region": "徐州",
        "type": "州",
        "modern_location": "江苏省徐州市",
        "description": "四战之地，陶谦让徐州于刘备。吕布夺徐州，曹操灭吕布取徐州。",
    },
    {
        "location_id": "yanzhou",
        "name": "兖州",
        "faction": "faction_wei",
        "region": "兖州",
        "type": "州",
        "modern_location": "山东省济宁市",
        "description": "曹操起家之地，入兖州破黄巾收青州兵，奠定基业。",
    },
    {
        "location_id": "jizhou",
        "name": "冀州",
        "faction": "faction_wei",
        "region": "冀州",
        "type": "州",
        "modern_location": "河北省冀州市",
        "description": "袁绍根基之地，官渡战后归曹操。人口稠密，兵源充足。",
    },
    {
        "location_id": "youzhou",
        "name": "幽州",
        "faction": None,
        "region": "幽州",
        "type": "州",
        "modern_location": "北京市",
        "description": "公孙瓒与袁绍争夺之地，刘备亦曾驻守。北方边塞要地。",
    },
    {
        "location_id": "bai_di_cheng",
        "name": "白帝城",
        "faction": "faction_shu",
        "region": "益州",
        "type": "城",
        "modern_location": "重庆市奉节县",
        "description": "刘备夷陵兵败后退守于此，托孤诸葛亮后病逝。'朝辞白帝彩云间'。",
    },
    {
        "location_id": "wuzhangyuan",
        "name": "五丈原",
        "faction": "faction_wei",
        "region": "关中",
        "type": "城",
        "modern_location": "陕西省宝鸡市",
        "description": "诸葛亮最后一次北伐驻军之地，星落秋风五丈原，鞠躬尽瘁死而后已。",
    },
    {
        "location_id": "dingjunshan",
        "name": "定军山",
        "faction": "faction_shu",
        "region": "益州",
        "type": "城",
        "modern_location": "陕西省勉县",
        "description": "黄忠斩夏侯渊之地，汉中之战关键战场。老将黄忠一战成名。",
    },
    {
        "location_id": "changbanpo",
        "name": "长坂坡",
        "faction": None,
        "region": "荆州",
        "type": "城",
        "modern_location": "湖北省当阳市",
        "description": "赵云单骑救主之地，张飞据水断桥。刘备败走长坂坡的惨烈战场。",
    },
    {
        "location_id": "hulao_pass",
        "name": "虎牢关",
        "faction": None,
        "region": "司隶",
        "type": "关",
        "modern_location": "河南省荥阳市",
        "description": "三英战吕布之地，讨董联盟关键战场。洛阳东面门户，险关要塞。",
    },
    {
        "location_id": "jiangling",
        "name": "江陵",
        "faction": "faction_wu",
        "region": "荆州",
        "type": "城",
        "modern_location": "湖北省荆州市",
        "description": "荆州核心重镇，赤壁后周瑜攻取江陵。关羽镇守荆州时以此为治所。",
    },
    {
        "location_id": "runan",
        "name": "汝南",
        "faction": None,
        "region": "豫州",
        "type": "郡",
        "modern_location": "河南省汝南县",
        "description": "袁绍袁术故里，四世三公之根。黄巾余党活跃之地。",
    },
    {
        "location_id": "beihai",
        "name": "北海",
        "faction": None,
        "region": "青州",
        "type": "郡",
        "modern_location": "山东省潍坊市",
        "description": "孔融治北海之地，太史慈突围求援于刘备。青州要地。",
    },
    {
        "location_id": "liaodong",
        "name": "辽东",
        "faction": None,
        "region": "幽州",
        "type": "郡",
        "modern_location": "辽宁省辽阳市",
        "description": "东北边陲，公孙氏割据之地。郭嘉遗计定辽东，曹操平定北方最后一步。",
    },
]


def get_location(location_id: str) -> dict | None:
    """根据 location_id 获取地点信息"""
    for loc in LOCATIONS:
        if loc["location_id"] == location_id:
            return loc
    return None
