"""三国演义人物关系数据 — ~48条关系"""

RELATIONSHIPS = [
    # ── 结义 ──
    {
        "rel_id": "rel_jieyi_liu_guan",
        "type": "结义",
        "from": "liu_bei",
        "to": "guan_yu",
        "year": 184,
        "description": "桃园结义，刘关张三兄弟，誓同生死。",
    },
    {
        "rel_id": "rel_jieyi_liu_zhang",
        "type": "结义",
        "from": "liu_bei",
        "to": "zhang_fei",
        "year": 184,
        "description": "桃园结义，刘关张三兄弟，誓同生死。",
    },
    {
        "rel_id": "rel_jieyi_guan_zhang",
        "type": "结义",
        "from": "guan_yu",
        "to": "zhang_fei",
        "year": 184,
        "description": "桃园结义，刘关张三兄弟，誓同生死。",
    },
    # ── 君臣（蜀） ──
    {
        "rel_id": "rel_junchen_liu_zhuge",
        "type": "君臣",
        "from": "liu_bei",
        "to": "zhuge_liang",
        "year": 207,
        "description": "三顾茅庐，诸葛亮为刘备军师，后任蜀汉丞相。君臣相知，鱼水之交。",
    },
    {
        "rel_id": "rel_junchen_liu_zhaoyun",
        "type": "君臣",
        "from": "liu_bei",
        "to": "zhao_yun",
        "year": 200,
        "description": "赵云追随刘备，长坂坡单骑救主，忠心耿耿。",
    },
    {
        "rel_id": "rel_junchen_liu_huangzhong",
        "type": "君臣",
        "from": "liu_bei",
        "to": "huang_zhong",
        "year": 211,
        "description": "黄忠归刘备，定军山斩夏侯渊，老当益壮。",
    },
    {
        "rel_id": "rel_junchen_liu_machao",
        "type": "君臣",
        "from": "liu_bei",
        "to": "ma_chao",
        "year": 215,
        "description": "马超归刘备，五虎上将之一，镇守西平关。",
    },
    {
        "rel_id": "rel_junchen_liu_weiyan",
        "type": "君臣",
        "from": "liu_bei",
        "to": "wei_yan",
        "year": 211,
        "description": "魏延随刘备入蜀，屡立战功，后镇守汉中。",
    },
    # ── 君臣（魏） ──
    {
        "rel_id": "rel_junchen_cao_xiaohoudun",
        "type": "君臣",
        "from": "cao_cao",
        "to": "xiahou_dun",
        "year": 190,
        "description": "夏侯惇为曹操宗族大将，忠勇无双，拔矢啖睛。",
    },
    {
        "rel_id": "rel_junchen_cao_xiaohouyuan",
        "type": "君臣",
        "from": "cao_cao",
        "to": "xiahou_yuan",
        "year": 190,
        "description": "夏侯渊为曹操宗族大将，善千里奔袭，镇守汉中。",
    },
    {
        "rel_id": "rel_junchen_cao_zhangliao",
        "type": "君臣",
        "from": "cao_cao",
        "to": "zhang_liao",
        "year": 198,
        "description": "张辽归曹操，合肥威震逍遥津，曹魏第一名将。",
    },
    {
        "rel_id": "rel_junchen_cao_xuchu",
        "type": "君臣",
        "from": "cao_cao",
        "to": "xu_chu",
        "year": 197,
        "description": "许褚为曹操贴身护卫，号'虎痴'，忠心护主。",
    },
    {
        "rel_id": "rel_junchen_cao_guojia",
        "type": "君臣",
        "from": "cao_cao",
        "to": "guo_jia",
        "year": 196,
        "description": "郭嘉为曹操首席谋士，算无遗策，英年早逝。",
    },
    {
        "rel_id": "rel_junchen_cao_simayi",
        "type": "君臣",
        "from": "cao_cao",
        "to": "sima_yi",
        "year": 208,
        "description": "司马懿为曹操谋士，隐忍深谋，后夺曹魏大权。",
    },
    # ── 君臣（吴） ──
    {
        "rel_id": "rel_junchen_sun_zhouyu",
        "type": "君臣",
        "from": "sun_quan",
        "to": "zhou_yu",
        "year": 200,
        "description": "周瑜为东吴大都督，赤壁之战统军破曹。",
    },
    {
        "rel_id": "rel_junchen_sun_luxun",
        "type": "君臣",
        "from": "sun_quan",
        "to": "lu_xun",
        "year": 222,
        "description": "陆逊夷陵之战火烧连营，后任东吴丞相。",
    },
    {
        "rel_id": "rel_junchen_sun_lumeng",
        "type": "君臣",
        "from": "sun_quan",
        "to": "lu_meng",
        "year": 215,
        "description": "吕蒙白衣渡江取荆州，擒杀关羽。",
    },
    {
        "rel_id": "rel_junchen_sun_ganning",
        "type": "君臣",
        "from": "sun_quan",
        "to": "gan_ning",
        "year": 208,
        "description": "甘宁百骑劫魏营，东吴猛将。",
    },
    {
        "rel_id": "rel_junchen_sun_huanggai",
        "type": "君臣",
        "from": "sun_quan",
        "to": "huang_gai",
        "year": 208,
        "description": "黄盖赤壁献苦肉计，火烧曹营，三朝老将。",
    },
    # ── 对手 ──
    {
        "rel_id": "rel_duishou_cao_liu",
        "type": "对手",
        "from": "cao_cao",
        "to": "liu_bei",
        "year": 196,
        "description": "曹操与刘备，'天下英雄唯使君与操耳'。一生对手，争夺天下。",
    },
    {
        "rel_id": "rel_duishou_cao_yuanshao",
        "type": "对手",
        "from": "cao_cao",
        "to": "yuan_shao",
        "year": 190,
        "description": "曹操与袁绍，从少时好友到官渡决战，胜者统一北方。",
    },
    {
        "rel_id": "rel_duishou_cao_zhouyu",
        "type": "对手",
        "from": "cao_cao",
        "to": "zhou_yu",
        "year": 208,
        "description": "赤壁之战，周瑜以火攻大败曹操，曹操叹'既生瑜何生亮'实为演义虚构。",
    },
    {
        "rel_id": "rel_duishou_liu_lubu",
        "type": "对手",
        "from": "liu_bei",
        "to": "lu_bu",
        "year": 196,
        "description": "吕布夺刘备徐州，后刘备助曹操灭吕布。反复恩怨。",
    },
    {
        "rel_id": "rel_duishou_zhuge_simayi",
        "type": "对手",
        "from": "zhuge_liang",
        "to": "sima_yi",
        "year": 228,
        "description": "诸葛亮与司马懿，六出祁山对峙多年。空城计、木门道，棋逢对手。",
    },
    {
        "rel_id": "rel_duishou_guan_lubu",
        "type": "对手",
        "from": "guan_yu",
        "to": "lu_bu",
        "year": 190,
        "description": "虎牢关三英战吕布，关羽与吕布武力巅峰对决。",
    },
    {
        "rel_id": "rel_duishou_liu_sunquan",
        "type": "对手",
        "from": "liu_bei",
        "to": "sun_quan",
        "year": 219,
        "description": "荆州之争使孙刘联盟破裂，夷陵之战兵戎相见。先盟后敌。",
    },
    # ── 师徒 ──
    {
        "rel_id": "rel_shitu_zhuge_jiangwei",
        "type": "师徒",
        "from": "zhuge_liang",
        "to": "jiang_wei",
        "year": 228,
        "description": "诸葛亮收姜维为徒，传授兵法衣钵。姜维继承北伐遗志。",
    },
    {
        "rel_id": "rel_shitu_simayi_simazhao",
        "type": "师徒",
        "from": "sima_yi",
        "to": "sima_zhao",
        "year": 249,
        "description": "司马懿传位于司马昭，父子同心夺取曹魏大权。",
    },
    # ── 同僚 ──
    {
        "rel_id": "rel_tongliao_zhouyu_lumeng",
        "type": "同僚",
        "from": "zhou_yu",
        "to": "lu_meng",
        "year": 208,
        "description": "周瑜与吕蒙，东吴两代大都督，先后统军抗曹。",
    },
    {
        "rel_id": "rel_tongliao_zhouyu_huanggai",
        "type": "同僚",
        "from": "zhou_yu",
        "to": "huang_gai",
        "year": 208,
        "description": "赤壁之战，周瑜与黄盖合演苦肉计，火烧曹营。",
    },
    {
        "rel_id": "rel_tongliao_guojia_simayi",
        "type": "同僚",
        "from": "guo_jia",
        "to": "sima_yi",
        "year": 208,
        "description": "郭嘉与司马懿，曹操前后任谋士。郭嘉早逝后司马懿渐掌大权。",
    },
    # ── 父子 ──
    {
        "rel_id": "rel_fuzi_cao_caopi",
        "type": "父子",
        "from": "cao_cao",
        "to": "cao_pi",
        "year": 187,
        "description": "曹操与曹丕，父子相承。曹丕继魏王位后代汉称帝。",
    },
    {
        "rel_id": "rel_fuzi_sunjian_sunce",
        "type": "父子",
        "from": "sun_jian",
        "to": "sun_ce",
        "year": 175,
        "description": "孙坚与孙策，江东猛虎生小霸王。孙策继承父业横扫江东。",
    },
    {
        "rel_id": "rel_fuzi_sunjian_sunquan",
        "type": "父子",
        "from": "sun_jian",
        "to": "sun_quan",
        "year": 182,
        "description": "孙坚与孙权，孙权承父兄之业据守江东，建立东吴。",
    },
    {
        "rel_id": "rel_xiongdi_sunce_sunquan",
        "type": "兄弟",
        "from": "sun_ce",
        "to": "sun_quan",
        "year": 200,
        "description": "孙策与孙权，兄弟相承。孙策临终托付'内事不决问张昭，外事不决问周瑜'。",
    },
    # ── 联姻 ──
    {
        "rel_id": "rel_lianyin_liu_sun_shangxiang",
        "type": "联姻",
        "from": "liu_bei",
        "to": "sun_quan",
        "year": 209,
        "description": "孙刘联姻，孙权嫁妹孙尚香于刘备，巩固联盟。后孙尚香返吴未归。",
    },
    # ── 对手（补充） ──
    {
        "rel_id": "rel_duishou_yuanshao_gongsun_zan",
        "type": "对手",
        "from": "yuan_shao",
        "to": "gongsun_zan",
        "year": 191,
        "description": "袁绍与公孙瓒争夺冀州，界桥之战袁绍胜，公孙瓒退守幽州。",
    },
    {
        "rel_id": "rel_duishou_yuan_shao_yuan_shu",
        "type": "对手",
        "from": "yuan_shao",
        "to": "yuan_shu",
        "year": 194,
        "description": "袁绍与袁术兄弟反目，各据一方。袁术称帝后袁绍亦与其决裂。",
    },
    # ── 君臣（补充） ──
    {
        "rel_id": "rel_junchen_liu_bei_pangtong",
        "type": "君臣",
        "from": "liu_bei",
        "to": "pang_tong",
        "year": 209,
        "description": "庞统归刘备，与诸葛亮同为军师中郎将。'卧龙凤雏'齐佐刘备。",
    },
    {
        "rel_id": "rel_junchen_dong_zhuo_lubu",
        "type": "君臣",
        "from": "dong_zhuo",
        "to": "lu_bu",
        "year": 189,
        "description": "董卓收吕布为义子，吕布勇冠三军。然王允连环计离间，吕布终杀董卓。",
    },
    {
        "rel_id": "rel_junchen_yuanshao_guojia",
        "type": "君臣",
        "from": "yuan_shao",
        "to": "guo_jia",
        "year": 190,
        "description": "郭嘉初投袁绍，见其难成大事而离去，后归曹操成为首席谋士。",
    },
    # ── 同僚（补充） ──
    {
        "rel_id": "rel_tongliao_zhuge_liang_pangtong",
        "type": "同僚",
        "from": "zhuge_liang",
        "to": "pang_tong",
        "year": 209,
        "description": "卧龙凤雏，齐名当世。同辅刘备，庞统早逝后诸葛亮独撑蜀汉。",
    },
    {
        "rel_id": "rel_tongliao_guan_yu_zhang_fei",
        "type": "同僚",
        "from": "guan_yu",
        "to": "zhang_fei",
        "year": 184,
        "description": "关羽张飞，万人之敌，同随刘备征战四方。关张之勇为世所惮。",
    },
    {
        "rel_id": "rel_tongliao_xiahou_dun_xiahou_yuan",
        "type": "同僚",
        "from": "xiahou_dun",
        "to": "xiahou_yuan",
        "year": 190,
        "description": "夏侯惇夏侯渊，曹魏宗族双壁，同为曹操左膀右臂。",
    },
    {
        "rel_id": "rel_tongliao_luxun_lumeng",
        "type": "同僚",
        "from": "lu_xun",
        "to": "lu_meng",
        "year": 220,
        "description": "陆逊与吕蒙，东吴后起之秀。吕蒙荐陆逊代己守荆州。",
    },
    # ── 对手（补充） ──
    {
        "rel_id": "rel_duishou_cao_cao_lubu",
        "type": "对手",
        "from": "cao_cao",
        "to": "lu_bu",
        "year": 194,
        "description": "曹操与吕布争夺兖州，后联合刘备灭吕布于下邳。",
    },
    {
        "rel_id": "rel_duishou_ma_chao_cao_cao",
        "type": "对手",
        "from": "ma_chao",
        "to": "cao_cao",
        "year": 211,
        "description": "马超为报父仇起兵反曹，杀得曹操割须弃袍，后中反间计败走归刘备。",
    },
    # ── 父子（补充） ──
    {
        "rel_id": "rel_fuzi_simayi_simazhao",
        "type": "父子",
        "from": "sima_yi",
        "to": "sima_zhao",
        "year": 211,
        "description": "司马懿与司马昭，父子相承。司马懿夺权，司马昭灭蜀，为晋代魏奠基。",
    },
]


def get_relationships_of(character_id: str) -> list[dict]:
    """获取与某人物相关的所有关系"""
    return [
        r
        for r in RELATIONSHIPS
        if r["from"] == character_id or r["to"] == character_id
    ]
